apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bd-helloworld-deployment
  labels:
     app: bd-helloworld-deployment
spec:
  replicas: 2
  selector:
     matchLabels:
        app: bd-helloworld-deployment
  template:
    metadata:
      labels:
        app: bd-helloworld-deployment
    spec:
      containers:
        - name: bd-helloworld
          image: webapp:1
          # for local development against minikube registry
          #imagePullPolicy: Never        
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bd-helloworld-service
spec:
  ports:
    - name: bd-helloworld-port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: bd-helloworld-deployment
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: bd-helloworld-via-ingress
spec:
  rules:
  - host: bryan-workday-demo.us-south.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: bd-helloworld-service
          servicePort: 80
        path: /helloworld

     
    
